name: Gosec

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sectest:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...